<a href="https://colab.research.google.com/github/sunil5058/AI-ML/blob/main/AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task 1**
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [7]:
import numpy as np
arr_empty =np.empty ((2,2))
print (arr_empty)

arr_ones =np.ones((4,2))
print (arr_ones)


arr_full=np.full((3,3),7)
print(arr_full)

a=np.array([[1,2],[3,4]])
arr_zero_like=np.zeros_like(a)
print(arr_zero_like)


new_list=[1,2,3,4]
arr_from_list=np.array(new_list)
print (arr_from_list)


[[3.58856616e-315 0.00000000e+000]
 [1.27126159e+232 0.00000000e+000]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0]
 [0 0]]
[1 2 3 4]


**Task 2**
: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [18]:
arr1=np.arange(10,50)
print(arr1)

arr2=np.arange(9).reshape(3,3)
print(arr2)


identity_matrix=np.eye(3)
print(identity_matrix)


rand_arr=np.random.random(30)
print("mean:", rand_arr.mean())

arr_random=np.random.random((10,10))
print("minimum :",arr_random.min())
print("maximum :",arr_random.max())



arr_zero=np.zeros(10)
arr_zero[4]=1
print(arr_zero)



arr=np.array([1,2,0,0,4,0])
reverse_arr=arr[::-1]
print(reverse_arr)




arr_border=np.ones((5,5))
arr_border[1:-1,1:-1]=0
print(arr_border)


checkerboard=np.zeros((8,8))
checkerboard[1::2,::2]=1
checkerboard[::2,1::2]=1
print(checkerboard)






[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
mean: 0.4983456185848366
minimum : 0.018861897135141414
maximum : 0.9989799655720827
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


***Problem - 3***: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [30]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);
print(x)
print(y)
print(v)
print(w)


add=np.add(x,y)
print(add)

sub_xy=np.subtract(x,y)
print(sub_xy)

mul_x=np.multiply(x,3)
print(mul_x)

square_x=np.square(x)
print(square_x)


dot_vw=np.dot(v,w)
dot_xv=np.dot(x,v)
dot_xy=np.dot(x,y)
print(dot_vw)
print(dot_xv)
print(dot_xy)



concat_xy_row = np.concatenate((x, y))
print(concat_xy_row)


concat_vw_col = np.vstack((v, w))
print(concat_vw_col)


concat_xv=np.concatenate((x,v))
print(concat_xv)


[[1 2]
 [3 5]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]
[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

***Problem - 4***: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [42]:


A = np.array([[3, 4],[7, 8]])
B = np.array([[5, 3],[2, 1]])

A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print(I)

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =", AB)
print("BA =", BA)











[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB = [[23 13]
 [51 29]]
BA = [[36 44]
 [13 16]]
